// Generated by apps/desktop/scripts/generate-office-object-catalog.cjs.

export interface OfficeObjectVariant {
  readonly scale: 16 | 32 | 48;
  readonly path: string;
  readonly w: number;
  readonly h: number;
  readonly bounds: {
    readonly x: number;
    readonly y: number;
    readonly w: number;
    readonly h: number;
  };
}

export interface OfficeObjectAsset {
  readonly id: string;
  readonly sourceId: number;
  readonly variants: readonly OfficeObjectVariant[];
}

export const OFFICE_OBJECT_ASSETS: readonly OfficeObjectAsset[] = [
  {
    id: "office-object-001",
    sourceId: 1,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-001.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-002",
    sourceId: 2,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-002.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-003",
    sourceId: 3,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-003.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-004",
    sourceId: 4,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-004.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-005",
    sourceId: 5,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-005.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-006",
    sourceId: 6,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-006.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-007",
    sourceId: 7,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-007.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-008",
    sourceId: 8,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-008.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-009",
    sourceId: 9,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-009.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-010",
    sourceId: 10,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-010.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-011",
    sourceId: 11,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-011.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-012",
    sourceId: 12,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-012.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-013",
    sourceId: 13,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-013.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-014",
    sourceId: 14,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-014.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-015",
    sourceId: 15,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-015.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-016",
    sourceId: 16,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-016.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-017",
    sourceId: 17,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-017.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-018",
    sourceId: 18,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-018.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-019",
    sourceId: 19,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-019.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-020",
    sourceId: 20,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-020.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-021",
    sourceId: 21,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-021.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-022",
    sourceId: 22,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-022.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-023",
    sourceId: 23,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-023.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-024",
    sourceId: 24,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-024.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-025",
    sourceId: 25,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-025.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-026",
    sourceId: 26,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-026.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-027",
    sourceId: 27,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-027.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-028",
    sourceId: 28,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-028.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-029",
    sourceId: 29,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-029.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-030",
    sourceId: 30,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-030.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-031",
    sourceId: 31,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-031.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-032",
    sourceId: 32,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-032.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-033",
    sourceId: 33,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-033.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-034",
    sourceId: 34,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-034.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-035",
    sourceId: 35,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-035.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-036",
    sourceId: 36,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-036.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-037",
    sourceId: 37,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-037.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-038",
    sourceId: 38,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-038.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-039",
    sourceId: 39,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-039.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-040",
    sourceId: 40,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-040.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-041",
    sourceId: 41,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-041.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-042",
    sourceId: 42,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-042.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-043",
    sourceId: 43,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-043.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-044",
    sourceId: 44,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-044.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-045",
    sourceId: 45,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-045.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-046",
    sourceId: 46,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-046.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-047",
    sourceId: 47,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-047.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-048",
    sourceId: 48,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-048.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-049",
    sourceId: 49,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-049.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-050",
    sourceId: 50,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-050.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-051",
    sourceId: 51,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-051.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-052",
    sourceId: 52,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-052.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-053",
    sourceId: 53,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-053.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-054",
    sourceId: 54,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-054.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-055",
    sourceId: 55,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-055.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-056",
    sourceId: 56,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-056.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-057",
    sourceId: 57,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-057.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-058",
    sourceId: 58,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-058.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-059",
    sourceId: 59,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-059.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-060",
    sourceId: 60,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-060.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-061",
    sourceId: 61,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-061.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-062",
    sourceId: 62,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-062.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-063",
    sourceId: 63,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-063.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-064",
    sourceId: 64,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-064.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-065",
    sourceId: 65,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-065.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-066",
    sourceId: 66,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-066.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-067",
    sourceId: 67,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-067.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-068",
    sourceId: 68,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-068.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-069",
    sourceId: 69,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-069.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-070",
    sourceId: 70,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-070.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-071",
    sourceId: 71,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-071.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-072",
    sourceId: 72,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-072.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-073",
    sourceId: 73,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-073.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-074",
    sourceId: 74,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-074.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-075",
    sourceId: 75,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-075.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-076",
    sourceId: 76,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-076.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-077",
    sourceId: 77,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-077.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-078",
    sourceId: 78,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-078.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-079",
    sourceId: 79,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-079.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 30, h: 14 },
      },
    ],
  },
  {
    id: "office-object-080",
    sourceId: 80,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-080.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-081",
    sourceId: 81,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-081.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-082",
    sourceId: 82,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-082.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 14 },
      },
    ],
  },
  {
    id: "office-object-083",
    sourceId: 83,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-083.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-084",
    sourceId: 84,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-084.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-085",
    sourceId: 85,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-085.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 24 },
      },
    ],
  },
  {
    id: "office-object-086",
    sourceId: 86,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-086.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-087",
    sourceId: 87,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-087.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-088",
    sourceId: 88,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-088.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-089",
    sourceId: 89,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-089.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-090",
    sourceId: 90,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-090.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-091",
    sourceId: 91,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-091.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-092",
    sourceId: 92,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-092.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-093",
    sourceId: 93,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-093.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-094",
    sourceId: 94,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-094.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-095",
    sourceId: 95,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-095.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-096",
    sourceId: 96,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-096.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 48, w: 28, h: 34 },
      },
    ],
  },
  {
    id: "office-object-097",
    sourceId: 97,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-097.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 48, w: 28, h: 34 },
      },
    ],
  },
  {
    id: "office-object-098",
    sourceId: 98,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-098.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 20, w: 32, h: 56 },
      },
    ],
  },
  {
    id: "office-object-099",
    sourceId: 99,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-099.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 40, w: 32, h: 36 },
      },
    ],
  },
  {
    id: "office-object-100",
    sourceId: 100,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-100.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 24, w: 24, h: 52 },
      },
    ],
  },
  {
    id: "office-object-101",
    sourceId: 101,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-101.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 46, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-102",
    sourceId: 102,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-102.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 46, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-103",
    sourceId: 103,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-103.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 42, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-104",
    sourceId: 104,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-104.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 42, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-105",
    sourceId: 105,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-105.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-106",
    sourceId: 106,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-106.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-107",
    sourceId: 107,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-107.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 46, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-108",
    sourceId: 108,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-108.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 46, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-109",
    sourceId: 109,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-109.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 42, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-110",
    sourceId: 110,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-110.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 42, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-111",
    sourceId: 111,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-111.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-112",
    sourceId: 112,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-112.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-113",
    sourceId: 113,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-113.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 52, w: 28, h: 32 },
      },
    ],
  },
  {
    id: "office-object-114",
    sourceId: 114,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-114.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 52, w: 28, h: 32 },
      },
    ],
  },
  {
    id: "office-object-115",
    sourceId: 115,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-115.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 52, w: 28, h: 32 },
      },
    ],
  },
  {
    id: "office-object-116",
    sourceId: 116,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-116.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 54, w: 50, h: 28 },
      },
    ],
  },
  {
    id: "office-object-117",
    sourceId: 117,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-117.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 48, w: 26, h: 22 },
      },
    ],
  },
  {
    id: "office-object-118",
    sourceId: 118,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-118.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 48, w: 26, h: 22 },
      },
    ],
  },
  {
    id: "office-object-119",
    sourceId: 119,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-119.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 76, w: 20, h: 20 },
      },
    ],
  },
  {
    id: "office-object-120",
    sourceId: 120,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-120.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 10 },
      },
    ],
  },
  {
    id: "office-object-121",
    sourceId: 121,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-121.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-122",
    sourceId: 122,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-122.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 56, w: 32, h: 34 },
      },
    ],
  },
  {
    id: "office-object-123",
    sourceId: 123,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-123.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 40, w: 30, h: 56 },
      },
    ],
  },
  {
    id: "office-object-124",
    sourceId: 124,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-124.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 82, w: 32, h: 10 },
      },
    ],
  },
  {
    id: "office-object-125",
    sourceId: 125,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-125.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-126",
    sourceId: 126,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-126.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 56, w: 32, h: 34 },
      },
    ],
  },
  {
    id: "office-object-127",
    sourceId: 127,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-127.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 44, w: 30, h: 52 },
      },
    ],
  },
  {
    id: "office-object-128",
    sourceId: 128,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-128.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 70, w: 32, h: 10 },
      },
    ],
  },
  {
    id: "office-object-129",
    sourceId: 129,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-129.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-130",
    sourceId: 130,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-130.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 68, w: 32, h: 28 },
      },
    ],
  },
  {
    id: "office-object-131",
    sourceId: 131,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-131.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-132",
    sourceId: 132,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-132.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-133",
    sourceId: 133,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-133.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 68, w: 32, h: 28 },
      },
    ],
  },
  {
    id: "office-object-134",
    sourceId: 134,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-134.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-135",
    sourceId: 135,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-135.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 38, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-136",
    sourceId: 136,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-136.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 48, w: 26, h: 32 },
      },
    ],
  },
  {
    id: "office-object-137",
    sourceId: 137,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-137.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 38, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-138",
    sourceId: 138,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-138.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 38, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-139",
    sourceId: 139,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-139.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 48, w: 26, h: 32 },
      },
    ],
  },
  {
    id: "office-object-140",
    sourceId: 140,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-140.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 38, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-141",
    sourceId: 141,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-141.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 34 },
      },
    ],
  },
  {
    id: "office-object-142",
    sourceId: 142,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-142.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 34 },
      },
    ],
  },
  {
    id: "office-object-143",
    sourceId: 143,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-143.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 34 },
      },
    ],
  },
  {
    id: "office-object-144",
    sourceId: 144,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-144.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 34, w: 30, h: 34 },
      },
    ],
  },
  {
    id: "office-object-145",
    sourceId: 145,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-145.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 34, w: 30, h: 34 },
      },
    ],
  },
  {
    id: "office-object-146",
    sourceId: 146,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-146.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 34, w: 30, h: 34 },
      },
    ],
  },
  {
    id: "office-object-147",
    sourceId: 147,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-147.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 36, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-148",
    sourceId: 148,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-148.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 36 },
      },
    ],
  },
  {
    id: "office-object-149",
    sourceId: 149,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-149.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 38 },
      },
    ],
  },
  {
    id: "office-object-150",
    sourceId: 150,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-150.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 36, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-151",
    sourceId: 151,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-151.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 36 },
      },
    ],
  },
  {
    id: "office-object-152",
    sourceId: 152,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-152.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 30, h: 38 },
      },
    ],
  },
  {
    id: "office-object-153",
    sourceId: 153,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-153.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 72, w: 24, h: 24 },
      },
    ],
  },
  {
    id: "office-object-154",
    sourceId: 154,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-154.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 32, h: 30 },
      },
    ],
  },
  {
    id: "office-object-155",
    sourceId: 155,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-155.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 54, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-156",
    sourceId: 156,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-156.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 58, w: 32, h: 34 },
      },
    ],
  },
  {
    id: "office-object-157",
    sourceId: 157,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-157.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 66, w: 20, h: 30 },
      },
    ],
  },
  {
    id: "office-object-158",
    sourceId: 158,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-158.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 66, w: 20, h: 30 },
      },
    ],
  },
  {
    id: "office-object-159",
    sourceId: 159,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-159.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 66, w: 20, h: 30 },
      },
    ],
  },
  {
    id: "office-object-160",
    sourceId: 160,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-160.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 66, w: 20, h: 30 },
      },
    ],
  },
  {
    id: "office-object-161",
    sourceId: 161,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-161.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 76, w: 26, h: 20 },
      },
    ],
  },
  {
    id: "office-object-162",
    sourceId: 162,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-162.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 76, w: 26, h: 20 },
      },
    ],
  },
  {
    id: "office-object-163",
    sourceId: 163,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-163.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 52, w: 24, h: 20 },
      },
    ],
  },
  {
    id: "office-object-164",
    sourceId: 164,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-164.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 46, w: 48, h: 40 },
      },
    ],
  },
  {
    id: "office-object-165",
    sourceId: 165,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-165.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 70, w: 52, h: 26 },
      },
    ],
  },
  {
    id: "office-object-166",
    sourceId: 166,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-166.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 70, w: 52, h: 26 },
      },
    ],
  },
  {
    id: "office-object-167",
    sourceId: 167,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-167.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 46, w: 26, h: 30 },
      },
    ],
  },
  {
    id: "office-object-168",
    sourceId: 168,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-168.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 32, w: 26, h: 44 },
      },
    ],
  },
  {
    id: "office-object-169",
    sourceId: 169,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-169.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 32, w: 26, h: 44 },
      },
    ],
  },
  {
    id: "office-object-170",
    sourceId: 170,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-170.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 46, w: 60, h: 46 },
      },
    ],
  },
  {
    id: "office-object-171",
    sourceId: 171,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-171.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 46, w: 60, h: 46 },
      },
    ],
  },
  {
    id: "office-object-172",
    sourceId: 172,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-172.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 46, w: 60, h: 46 },
      },
    ],
  },
  {
    id: "office-object-173",
    sourceId: 173,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-173.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 16, w: 28, h: 60 },
      },
    ],
  },
  {
    id: "office-object-174",
    sourceId: 174,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-174.png",
        w: 64,
        h: 96,
        bounds: { x: 16, y: 32, w: 36, h: 46 },
      },
    ],
  },
  {
    id: "office-object-175",
    sourceId: 175,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-175.png",
        w: 64,
        h: 96,
        bounds: { x: 10, y: 10, w: 46, h: 68 },
      },
    ],
  },
  {
    id: "office-object-176",
    sourceId: 176,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-176.png",
        w: 64,
        h: 96,
        bounds: { x: 10, y: 10, w: 46, h: 68 },
      },
    ],
  },
  {
    id: "office-object-177",
    sourceId: 177,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-177.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 52, w: 50, h: 40 },
      },
    ],
  },
  {
    id: "office-object-178",
    sourceId: 178,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-178.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 52, w: 50, h: 40 },
      },
    ],
  },
  {
    id: "office-object-179",
    sourceId: 179,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-179.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 32, w: 24, h: 42 },
      },
    ],
  },
  {
    id: "office-object-180",
    sourceId: 180,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-180.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-181",
    sourceId: 181,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-181.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-182",
    sourceId: 182,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-182.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 32, w: 24, h: 42 },
      },
    ],
  },
  {
    id: "office-object-183",
    sourceId: 183,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-183.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-184",
    sourceId: 184,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-184.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-185",
    sourceId: 185,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-185.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 32, w: 24, h: 42 },
      },
    ],
  },
  {
    id: "office-object-186",
    sourceId: 186,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-186.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 32, h: 42 },
      },
    ],
  },
  {
    id: "office-object-187",
    sourceId: 187,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-187.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-188",
    sourceId: 188,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-188.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 68, w: 44, h: 28 },
      },
    ],
  },
  {
    id: "office-object-189",
    sourceId: 189,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-189.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 64, w: 44, h: 32 },
      },
    ],
  },
  {
    id: "office-object-190",
    sourceId: 190,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-190.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 64, w: 44, h: 22 },
      },
    ],
  },
  {
    id: "office-object-191",
    sourceId: 191,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-191.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 68, w: 44, h: 28 },
      },
    ],
  },
  {
    id: "office-object-192",
    sourceId: 192,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-192.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 64, w: 44, h: 32 },
      },
    ],
  },
  {
    id: "office-object-193",
    sourceId: 193,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-193.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 64, w: 44, h: 24 },
      },
    ],
  },
  {
    id: "office-object-194",
    sourceId: 194,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-194.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 36, w: 44, h: 52 },
      },
    ],
  },
  {
    id: "office-object-195",
    sourceId: 195,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-195.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 4, w: 44, h: 82 },
      },
    ],
  },
  {
    id: "office-object-196",
    sourceId: 196,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-196.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 44, w: 32, h: 36 },
      },
    ],
  },
  {
    id: "office-object-197",
    sourceId: 197,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-197.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 44, w: 32, h: 36 },
      },
    ],
  },
  {
    id: "office-object-198",
    sourceId: 198,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-198.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 44, w: 32, h: 36 },
      },
    ],
  },
  {
    id: "office-object-199",
    sourceId: 199,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-199.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 44, w: 32, h: 36 },
      },
    ],
  },
  {
    id: "office-object-200",
    sourceId: 200,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-200.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 40, w: 62, h: 48 },
      },
    ],
  },
  {
    id: "office-object-201",
    sourceId: 201,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-201.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 8, w: 56, h: 76 },
      },
    ],
  },
  {
    id: "office-object-202",
    sourceId: 202,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-202.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 8, w: 26, h: 76 },
      },
    ],
  },
  {
    id: "office-object-203",
    sourceId: 203,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-203.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 8, w: 56, h: 76 },
      },
    ],
  },
  {
    id: "office-object-204",
    sourceId: 204,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-204.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 40, w: 26, h: 48 },
      },
    ],
  },
  {
    id: "office-object-205",
    sourceId: 205,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-205.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 40, w: 62, h: 48 },
      },
    ],
  },
  {
    id: "office-object-206",
    sourceId: 206,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-206.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 40, w: 32, h: 48 },
      },
    ],
  },
  {
    id: "office-object-207",
    sourceId: 207,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-207.png",
        w: 64,
        h: 96,
        bounds: { x: 26, y: 10, w: 6, h: 86 },
      },
    ],
  },
  {
    id: "office-object-208",
    sourceId: 208,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-208.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 42 },
      },
    ],
  },
  {
    id: "office-object-209",
    sourceId: 209,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-209.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 10, w: 32, h: 86 },
      },
    ],
  },
  {
    id: "office-object-210",
    sourceId: 210,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-210.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 50, w: 28, h: 46 },
      },
    ],
  },
  {
    id: "office-object-211",
    sourceId: 211,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-211.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-212",
    sourceId: 212,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-212.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 22, h: 46 },
      },
    ],
  },
  {
    id: "office-object-213",
    sourceId: 213,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-213.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 50, w: 28, h: 46 },
      },
    ],
  },
  {
    id: "office-object-214",
    sourceId: 214,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-214.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-215",
    sourceId: 215,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-215.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 22, h: 46 },
      },
    ],
  },
  {
    id: "office-object-216",
    sourceId: 216,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-216.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 50, w: 28, h: 46 },
      },
    ],
  },
  {
    id: "office-object-217",
    sourceId: 217,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-217.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-218",
    sourceId: 218,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-218.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 22, h: 46 },
      },
    ],
  },
  {
    id: "office-object-219",
    sourceId: 219,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-219.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 50, w: 28, h: 46 },
      },
    ],
  },
  {
    id: "office-object-220",
    sourceId: 220,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-220.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-221",
    sourceId: 221,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-221.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 22, h: 46 },
      },
    ],
  },
  {
    id: "office-object-222",
    sourceId: 222,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-222.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 50, w: 28, h: 46 },
      },
    ],
  },
  {
    id: "office-object-223",
    sourceId: 223,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-223.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 32, h: 46 },
      },
    ],
  },
  {
    id: "office-object-224",
    sourceId: 224,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-224.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 22, h: 46 },
      },
    ],
  },
  {
    id: "office-object-225",
    sourceId: 225,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-225.png",
        w: 64,
        h: 96,
        bounds: { x: 12, y: 34, w: 52, h: 48 },
      },
    ],
  },
  {
    id: "office-object-226",
    sourceId: 226,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-226.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 20, h: 52 },
      },
    ],
  },
  {
    id: "office-object-227",
    sourceId: 227,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-227.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 36, w: 64, h: 46 },
      },
    ],
  },
  {
    id: "office-object-228",
    sourceId: 228,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-228.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 52, w: 20, h: 30 },
      },
    ],
  },
  {
    id: "office-object-229",
    sourceId: 229,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-229.png",
        w: 64,
        h: 96,
        bounds: { x: 12, y: 32, w: 52, h: 48 },
      },
    ],
  },
  {
    id: "office-object-230",
    sourceId: 230,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-230.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 20, h: 52 },
      },
    ],
  },
  {
    id: "office-object-231",
    sourceId: 231,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-231.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 34, w: 64, h: 46 },
      },
    ],
  },
  {
    id: "office-object-232",
    sourceId: 232,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-232.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 42, w: 28, h: 40 },
      },
    ],
  },
  {
    id: "office-object-233",
    sourceId: 233,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-233.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 34, w: 56, h: 46 },
      },
    ],
  },
  {
    id: "office-object-234",
    sourceId: 234,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-234.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 44, w: 18, h: 36 },
      },
    ],
  },
  {
    id: "office-object-235",
    sourceId: 235,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-235.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 34, w: 56, h: 46 },
      },
    ],
  },
  {
    id: "office-object-236",
    sourceId: 236,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-236.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 44, w: 18, h: 36 },
      },
    ],
  },
  {
    id: "office-object-237",
    sourceId: 237,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-237.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 76, w: 30, h: 20 },
      },
    ],
  },
  {
    id: "office-object-238",
    sourceId: 238,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-238.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 76, w: 30, h: 20 },
      },
    ],
  },
  {
    id: "office-object-239",
    sourceId: 239,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-239.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 76, w: 30, h: 20 },
      },
    ],
  },
  {
    id: "office-object-240",
    sourceId: 240,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-240.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 74, w: 56, h: 22 },
      },
    ],
  },
  {
    id: "office-object-241",
    sourceId: 241,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-241.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 80, w: 26, h: 16 },
      },
    ],
  },
  {
    id: "office-object-242",
    sourceId: 242,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-242.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 76, w: 20, h: 20 },
      },
    ],
  },
  {
    id: "office-object-243",
    sourceId: 243,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-243.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 78, w: 26, h: 18 },
      },
    ],
  },
  {
    id: "office-object-244",
    sourceId: 244,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-244.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 72, w: 16, h: 24 },
      },
    ],
  },
  {
    id: "office-object-245",
    sourceId: 245,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-245.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-246",
    sourceId: 246,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-246.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-247",
    sourceId: 247,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-247.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-248",
    sourceId: 248,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-248.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-249",
    sourceId: 249,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-249.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-250",
    sourceId: 250,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-250.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-251",
    sourceId: 251,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-251.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-252",
    sourceId: 252,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-252.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-253",
    sourceId: 253,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-253.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-254",
    sourceId: 254,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-254.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-255",
    sourceId: 255,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-255.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-256",
    sourceId: 256,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-256.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-257",
    sourceId: 257,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-257.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-258",
    sourceId: 258,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-258.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-259",
    sourceId: 259,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-259.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-260",
    sourceId: 260,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-260.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-261",
    sourceId: 261,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-261.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-262",
    sourceId: 262,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-262.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-263",
    sourceId: 263,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-263.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-264",
    sourceId: 264,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-264.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-265",
    sourceId: 265,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-265.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-266",
    sourceId: 266,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-266.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-267",
    sourceId: 267,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-267.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-268",
    sourceId: 268,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-268.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-269",
    sourceId: 269,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-269.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-270",
    sourceId: 270,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-270.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 42, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-271",
    sourceId: 271,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-271.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 42, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-272",
    sourceId: 272,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-272.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 64, w: 10, h: 28 },
      },
    ],
  },
  {
    id: "office-object-273",
    sourceId: 273,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-273.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 60, w: 20, h: 20 },
      },
    ],
  },
  {
    id: "office-object-274",
    sourceId: 274,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-274.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 64, w: 22, h: 20 },
      },
    ],
  },
  {
    id: "office-object-275",
    sourceId: 275,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-275.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 2, w: 32, h: 70 },
      },
    ],
  },
  {
    id: "office-object-276",
    sourceId: 276,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-276.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 2, w: 32, h: 70 },
      },
    ],
  },
  {
    id: "office-object-277",
    sourceId: 277,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-277.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-278",
    sourceId: 278,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-278.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-279",
    sourceId: 279,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-279.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 50, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-280",
    sourceId: 280,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-280.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 50, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-281",
    sourceId: 281,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-281.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-282",
    sourceId: 282,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-282.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-283",
    sourceId: 283,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-283.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-284",
    sourceId: 284,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-284.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-285",
    sourceId: 285,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-285.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-286",
    sourceId: 286,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-286.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-287",
    sourceId: 287,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-287.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-288",
    sourceId: 288,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-288.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-289",
    sourceId: 289,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-289.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-290",
    sourceId: 290,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-290.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-291",
    sourceId: 291,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-291.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-292",
    sourceId: 292,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-292.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-293",
    sourceId: 293,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-293.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-294",
    sourceId: 294,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-294.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-295",
    sourceId: 295,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-295.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-296",
    sourceId: 296,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-296.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-297",
    sourceId: 297,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-297.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-298",
    sourceId: 298,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-298.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-299",
    sourceId: 299,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-299.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-300",
    sourceId: 300,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-300.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-301",
    sourceId: 301,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-301.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 80, w: 32, h: 16 },
      },
    ],
  },
  {
    id: "office-object-302",
    sourceId: 302,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-302.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-303",
    sourceId: 303,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-303.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 64, w: 32, h: 32 },
      },
    ],
  },
  {
    id: "office-object-304",
    sourceId: 304,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-304.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 38 },
      },
    ],
  },
  {
    id: "office-object-305",
    sourceId: 305,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-305.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 32, w: 64, h: 64 },
      },
    ],
  },
  {
    id: "office-object-306",
    sourceId: 306,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-306.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 40, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-307",
    sourceId: 307,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-307.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 40, w: 24, h: 46 },
      },
    ],
  },
  {
    id: "office-object-308",
    sourceId: 308,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-308.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 60, w: 20, h: 20 },
      },
    ],
  },
  {
    id: "office-object-309",
    sourceId: 309,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-309.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 64, w: 20, h: 20 },
      },
    ],
  },
  {
    id: "office-object-310",
    sourceId: 310,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-310.png",
        w: 64,
        h: 96,
        bounds: { x: 20, y: 64, w: 10, h: 28 },
      },
    ],
  },
  {
    id: "office-object-311",
    sourceId: 311,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-311.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 2, w: 32, h: 70 },
      },
    ],
  },
  {
    id: "office-object-312",
    sourceId: 312,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-312.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 2, w: 32, h: 70 },
      },
    ],
  },
  {
    id: "office-object-313",
    sourceId: 313,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-313.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-314",
    sourceId: 314,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-314.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 66, w: 30, h: 30 },
      },
    ],
  },
  {
    id: "office-object-315",
    sourceId: 315,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-315.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-316",
    sourceId: 316,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-316.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 50, w: 30, h: 32 },
      },
    ],
  },
  {
    id: "office-object-317",
    sourceId: 317,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-317.png",
        w: 64,
        h: 96,
        bounds: { x: 12, y: 42, w: 48, h: 52 },
      },
    ],
  },
  {
    id: "office-object-318",
    sourceId: 318,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-318.png",
        w: 64,
        h: 96,
        bounds: { x: 12, y: 42, w: 48, h: 52 },
      },
    ],
  },
  {
    id: "office-object-319",
    sourceId: 319,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-319.png",
        w: 64,
        h: 96,
        bounds: { x: 10, y: 42, w: 50, h: 52 },
      },
    ],
  },
  {
    id: "office-object-320",
    sourceId: 320,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-320.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 14, w: 52, h: 64 },
      },
    ],
  },
  {
    id: "office-object-321",
    sourceId: 321,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-321.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 14, w: 52, h: 64 },
      },
    ],
  },
  {
    id: "office-object-322",
    sourceId: 322,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-322.png",
        w: 64,
        h: 96,
        bounds: { x: 8, y: 14, w: 52, h: 64 },
      },
    ],
  },
  {
    id: "office-object-323",
    sourceId: 323,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-323.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 24, w: 52, h: 54 },
      },
    ],
  },
  {
    id: "office-object-324",
    sourceId: 324,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-324.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 24, w: 52, h: 54 },
      },
    ],
  },
  {
    id: "office-object-325",
    sourceId: 325,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-325.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 24, w: 52, h: 54 },
      },
    ],
  },
  {
    id: "office-object-326",
    sourceId: 326,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-326.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 24, w: 52, h: 54 },
      },
    ],
  },
  {
    id: "office-object-327",
    sourceId: 327,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-327.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 24, w: 52, h: 54 },
      },
    ],
  },
  {
    id: "office-object-328",
    sourceId: 328,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-328.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 24, w: 52, h: 54 },
      },
    ],
  },
  {
    id: "office-object-329",
    sourceId: 329,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-329.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 40, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-330",
    sourceId: 330,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-330.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 42, w: 30, h: 40 },
      },
    ],
  },
  {
    id: "office-object-331",
    sourceId: 331,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-331.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 40, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-332",
    sourceId: 332,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-332.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 42, w: 30, h: 40 },
      },
    ],
  },
  {
    id: "office-object-333",
    sourceId: 333,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-333.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 40, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-334",
    sourceId: 334,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-334.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 42, w: 30, h: 40 },
      },
    ],
  },
  {
    id: "office-object-335",
    sourceId: 335,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-335.png",
        w: 64,
        h: 96,
        bounds: { x: 4, y: 40, w: 26, h: 42 },
      },
    ],
  },
  {
    id: "office-object-336",
    sourceId: 336,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-336.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 42, w: 30, h: 40 },
      },
    ],
  },
  {
    id: "office-object-337",
    sourceId: 337,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-337.png",
        w: 64,
        h: 96,
        bounds: { x: 6, y: 54, w: 24, h: 30 },
      },
    ],
  },
  {
    id: "office-object-338",
    sourceId: 338,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-338.png",
        w: 64,
        h: 96,
        bounds: { x: 0, y: 56, w: 32, h: 40 },
      },
    ],
  },
  {
    id: "office-object-339",
    sourceId: 339,
    variants: [
      {
        scale: 32,
        path: "workspace-kit/office-objects/32/modern-office-32-339.png",
        w: 64,
        h: 96,
        bounds: { x: 2, y: 46, w: 62, h: 50 },
      },
    ],
  },
];
