import { z } from "zod";
import rawLayout from "@/renderer/game/office-design.json";
import { DEPTH } from "@/renderer/game/config";
import {
  OFFICE_OBJECT_ASSETS,
  type OfficeObjectVariant as CatalogVariant,
} from "@/renderer/game/office-object-catalog.generated";

export interface PixelPoint {
  readonly x: number;
  readonly y: number;
}

export type OfficeLayer = "floor" | "object" | "overhead";

export interface OfficeObjectPlacement {
  readonly id: string;
  readonly key: string;
  readonly path: string;
  readonly x: number;
  readonly y: number;
  readonly depth: number;
  readonly flipX: boolean;
  readonly flipY: boolean;
}

const OFFICE_OBJECT_SCALE = 32;

// office-design.json is generated by scripts/generate-office-design2.cjs: every
// structure tile and furnishing is a placed object over an authored collision
// grid with real walkable lanes. Parse it at the boundary into typed structures.
const rectSchema = z.object({ x: z.number(), y: z.number(), w: z.number(), h: z.number() });
const pointSchema = z.object({ x: z.number(), y: z.number() });
const objectSchema = z.object({
  id: z.string(),
  x: z.number(),
  y: z.number(),
  layer: z.enum(["floor", "object", "overhead"]),
  anchorY: z.number(),
  flipX: z.boolean().optional(),
  flipY: z.boolean().optional(),
  path: z.string().optional(),
  bounds: rectSchema.optional(),
});
const layoutSchema = z.object({
  tile: z.number(),
  width: z.number(),
  height: z.number(),
  cell: z.number(),
  cols: z.number(),
  rows: z.number(),
  spawn: pointSchema,
  objects: z.array(objectSchema),
  collision: z.array(z.string()),
  workSeats: z.array(pointSchema),
});

const LAYOUT = layoutSchema.parse(rawLayout);

/** The full parsed layout (for the in-app office builder to load + edit). */
export type OfficeLayoutData = z.infer<typeof layoutSchema>;
export const OFFICE_LAYOUT_RAW: OfficeLayoutData = LAYOUT;

// These are `let` because the runtime layout can be overridden by the player's
// saved office (applyOfficeLayout, called from store.refresh before the scene boots).
// ES live bindings mean importers see the updated values.
export let OFFICE_W = LAYOUT.width;
export let OFFICE_H = LAYOUT.height;
export let OFFICE_SPAWN: PixelPoint = LAYOUT.spawn;
export let OFFICE_WORK_SEATS: readonly PixelPoint[] = LAYOUT.workSeats;

export let OFFICE_CELL = LAYOUT.cell;
export let OFFICE_COLS = LAYOUT.cols;
export let OFFICE_ROWS = LAYOUT.rows;
export let OFFICE_SOLID_GRID: readonly (readonly boolean[])[] = LAYOUT.collision.map((row) =>
  Array.from(row, (ch) => ch === "1"),
);
export function officeSolidAt(x: number, y: number): boolean {
  const c = Math.floor(x / OFFICE_CELL);
  const r = Math.floor(y / OFFICE_CELL);
  if (r < 0 || c < 0 || r >= OFFICE_ROWS || c >= OFFICE_COLS) return true;
  return OFFICE_SOLID_GRID[r]?.[c] ?? true;
}

function catalogVariant(id: string): CatalogVariant | null {
  const asset = OFFICE_OBJECT_ASSETS.find((candidate) => candidate.id === id);
  if (!asset) return null;
  return asset.variants.find((variant) => variant.scale === OFFICE_OBJECT_SCALE) ?? null;
}

function objectTextureKey(id: string): string {
  return `office-object-sprite-${id}`;
}
function resolvePath(obj: z.infer<typeof objectSchema>): string {
  if (obj.path) return obj.path;
  const variant = catalogVariant(obj.id);
  if (!variant) throw new Error(`Missing office object asset: ${obj.id}`);
  return variant.path;
}

// floor decals below actors; object band y-sorts by floor-contact (the +0.5
// biases furniture to win ties, so the character draws behind what it stands at).
const OVERHEAD_BASE = 1_500_000;
export function depthFor(layer: OfficeLayer, anchorY: number): number {
  if (layer === "floor") return DEPTH.ground + 1 + anchorY * 1e-4;
  if (layer === "overhead") return OVERHEAD_BASE + anchorY;
  return DEPTH.entityBase + anchorY + 0.5;
}

function placementsOf(objects: OfficeLayoutData["objects"]): readonly OfficeObjectPlacement[] {
  return objects.map((obj) => ({
    id: obj.id,
    key: objectTextureKey(obj.id),
    path: resolvePath(obj),
    x: obj.x,
    y: obj.y,
    depth: depthFor(obj.layer, obj.anchorY),
    flipX: obj.flipX ?? false,
    flipY: obj.flipY ?? false,
  }));
}

export let OFFICE_OBJECT_PLACEMENTS: readonly OfficeObjectPlacement[] = placementsOf(LAYOUT.objects);

/**
 * Replace the live office layout (the player's saved office from disk overrides the
 * bundled default). Call BEFORE the Phaser scene boots — store.refresh awaits the
 * disk layout, so preload/buildRoom see these updated bindings.
 */
/** Validate an arbitrary value as a layout (for the builder to load a saved file). */
export function parseOfficeLayout(raw: unknown): OfficeLayoutData {
  return layoutSchema.parse(raw);
}

export function applyOfficeLayout(raw: unknown): void {
  const L = layoutSchema.parse(raw);
  OFFICE_W = L.width;
  OFFICE_H = L.height;
  OFFICE_SPAWN = L.spawn;
  OFFICE_WORK_SEATS = L.workSeats;
  OFFICE_CELL = L.cell;
  OFFICE_COLS = L.cols;
  OFFICE_ROWS = L.rows;
  OFFICE_SOLID_GRID = L.collision.map((row) => Array.from(row, (ch) => ch === "1"));
  OFFICE_OBJECT_PLACEMENTS = placementsOf(L.objects);
}
