import rawLayout from "@/renderer/game/office-design.json";
import { DEPTH } from "@/renderer/game/config";
import type { JsonValue } from "@/shared/json";
import {
  officeLayoutSchema,
  parseOfficeLayout,
  type OfficeLayer,
  type OfficeLayoutData,
  type OfficeObjectDef,
  type OfficePoi,
  type OfficeSeat,
  type PixelPoint,
} from "@/shared/office-layout-schema";
import { walkGridOf, type WalkGrid } from "@/shared/office-grid";
import {
  OFFICE_OBJECT_ASSETS,
  type OfficeObjectVariant as CatalogVariant,
} from "@/renderer/game/office-object-catalog.generated";

export type { OfficeLayer, OfficeLayoutData, OfficePoi, OfficeSeat, PixelPoint };
export { parseOfficeLayout };

export interface OfficeObjectPlacement {
  readonly id: string;
  readonly key: string;
  readonly path: string;
  readonly x: number;
  readonly y: number;
  readonly depth: number;
  readonly flipX: boolean;
  readonly flipY: boolean;
}

const OFFICE_OBJECT_SCALE = 32;

// office-design.json is generated by scripts/generate-office-design2.cjs: every
// structure tile and furnishing is a placed object over an authored collision
// grid with real walkable lanes. The schema (and what each field means) lives
// in shared/office-layout-schema.ts, because main validates the same file
// before it writes it. The bundled default is always the current version (the
// migrating parser is for files from disk), so it parses strictly, at module load.
const LAYOUT = officeLayoutSchema.parse(rawLayout);

/** The full parsed layout (for the in-app office builder to load + edit). */
export const OFFICE_LAYOUT_RAW: OfficeLayoutData = LAYOUT;

// These are `let` because the runtime layout can be overridden by the player's
// saved office (applyOfficeLayout, called from store.refresh before the scene boots).
// ES live bindings mean importers see the updated values.
export let OFFICE_W = LAYOUT.width;
export let OFFICE_H = LAYOUT.height;
export let OFFICE_SPAWN: PixelPoint = LAYOUT.spawn;
/** Where hires walk in from and released employees walk out to. */
export let OFFICE_DOOR: PixelPoint = LAYOUT.door;
export let OFFICE_SEATS: readonly OfficeSeat[] = LAYOUT.seats;
export let OFFICE_POIS: readonly OfficePoi[] = LAYOUT.pois;

export let OFFICE_CELL = LAYOUT.cell;
export let OFFICE_COLS = LAYOUT.cols;
export let OFFICE_ROWS = LAYOUT.rows;
/** The collision grid the scene walks, probes and paths over. */
export let OFFICE_GRID: WalkGrid = walkGridOf(LAYOUT);

function catalogVariant(id: string): CatalogVariant | null {
  const asset = OFFICE_OBJECT_ASSETS.find((candidate) => candidate.id === id);
  if (!asset) return null;
  return asset.variants.find((variant) => variant.scale === OFFICE_OBJECT_SCALE) ?? null;
}

function objectTextureKey(id: string): string {
  return `office-object-sprite-${id}`;
}
function resolvePath(obj: OfficeObjectDef): string {
  if (obj.path) return obj.path;
  const variant = catalogVariant(obj.id);
  if (!variant) throw new Error(`Missing office object asset: ${obj.id}`);
  return variant.path;
}

/**
 * Spacing between two neighbours in a flat stack. Small enough that a band of
 * STACK_STEP⁻¹ objects (a million) still cannot reach the band above it, so no
 * decal can ever climb out of the ground band or paint over a speech bubble.
 */
const STACK_STEP = 1e-3;

/**
 * Where a placed object draws, given its position in the paint-ordered array.
 *
 * The ground and overhead bands are flat stacks: they have no floor line, so they
 * paint in authored order and `index` alone separates them. Only the entity band
 * y-sorts — furniture and actors share it, sorting on floor contact (the +0.5
 * biases furniture to win ties, so a character draws behind what they stand at).
 */
function depthFor(obj: OfficeObjectDef, index: number): number {
  switch (obj.layer) {
    case "floor":
      return DEPTH.ground + STACK_STEP * (index + 1);
    case "overhead":
      return DEPTH.overhead + STACK_STEP * (index + 1);
    case "object":
      return DEPTH.entityBase + obj.anchorY + 0.5;
  }
}

/** All paint order needs of a placed object: its band, and its floor line if it has one. */
export type PaintOrdered =
  | { readonly layer: "floor" }
  | { readonly layer: "overhead" }
  | { readonly layer: "object"; readonly anchorY: number };

const BAND = { floor: 0, object: 1, overhead: 2 } satisfies Record<OfficeLayer, number>;

/**
 * Orders two placed objects back to front — the one comparator the game, the builder and
 * the render oracles all sort by, so what you author is what you see.
 *
 * Bands stack; inside the entity band, objects y-sort on their floor line. The flat bands
 * have no sort key and return 0 here, so they keep their list order — meaning every sort
 * through this MUST be stable (Array#sort and #toSorted are).
 */
export function comparePaintOrder(a: PaintOrdered, b: PaintOrdered): number {
  return (
    BAND[a.layer] - BAND[b.layer] ||
    (a.layer === "object" && b.layer === "object" ? a.anchorY - b.anchorY : 0)
  );
}

function placementsOf(objects: OfficeLayoutData["objects"]): readonly OfficeObjectPlacement[] {
  return objects.map((obj, index) => ({
    id: obj.id,
    key: objectTextureKey(obj.id),
    path: resolvePath(obj),
    x: obj.x,
    y: obj.y,
    depth: depthFor(obj, index),
    flipX: obj.flipX ?? false,
    flipY: obj.flipY ?? false,
  }));
}

export let OFFICE_OBJECT_PLACEMENTS: readonly OfficeObjectPlacement[] = placementsOf(
  LAYOUT.objects,
);

/**
 * Replace the live office layout (the player's saved office from disk overrides the
 * bundled default). Call BEFORE the Phaser scene boots — store.refresh awaits the
 * disk layout, so preload/buildRoom see these updated bindings. An older schema on
 * disk is upgraded on the way in; a file that fits no schema throws.
 */
export function applyOfficeLayout(raw: JsonValue): void {
  const L = parseOfficeLayout(raw);
  OFFICE_W = L.width;
  OFFICE_H = L.height;
  OFFICE_SPAWN = L.spawn;
  OFFICE_DOOR = L.door;
  OFFICE_SEATS = L.seats;
  OFFICE_POIS = L.pois;
  OFFICE_CELL = L.cell;
  OFFICE_COLS = L.cols;
  OFFICE_ROWS = L.rows;
  OFFICE_GRID = walkGridOf(L);
  OFFICE_OBJECT_PLACEMENTS = placementsOf(L.objects);
}
